# src/utilidades/estados_juego.py

# --- ESTADOS DEL JUEGO ---
ESTADO_MENU = "MENU"
ESTADO_JUEGO = "JUEGO"
ESTADO_VICTORIA = "VICTORIA"
ESTADO_DERROTA = "DERROTA"
ESTADO_SALIR = "SALIR"
ESTADO_PUNTUACIONES = "PUNTUACIONES"
